package parse

func SepararEtiqueta(linha string, etiqueta *Etiqueta) {
	// PARAMOS AQUI!!!!!
	// TODO: PARA CADA LINHA, COMEÇAR A GERAR UMA NOVA ETIQUETA
	//TODO LEMBRAR DE FAZER O HASH DA ETIQUETA
	// TODO LEMBRAR QUE NO FINAL DA ETIQUETA DEVE LIMPAR O PONTEIRO DA ETIQUETA
	// NÃO ESQUECER DE ANEXAR O PONTEIRO DE ETIQUETA AO PONTEIRO DE ARQUIVO

}
